# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
    - name: Test variable
      run : echo "$GITHUB_REF"

    - name : Set environment variables
      if: ${{env.GITHUB_REF == 'refs/heads/master'}}
      run : |
         echo "::set-env name=collection::10471783-2682b409-5169-4e2d-9a65-6c0b74f57573"

    - uses: actions/checkout@master
    - uses: matt-ball/newman-action@master

      with:
        apiKey: ${{ secrets.POSTMAN_API_KEY }}
        collection: $collection
        environment: 10471783-4f2f1481-bb2d-46e0-8080-abf57bf5bfee

